### PR TITLE
fetch only specific keys from all data

### PR DESCRIPTION
**Pull request by builder555**

### CODE REVIEW

**Comment by builder555** [comment]
@Adwaith-Rajesh @fredysomy are you guys around?

**Comment by builder555** [comment]
@Adwaith-Rajesh do you want to add a couple of maintainers who can manage the PRs? 
Or if this project is abandoned, I can take over.

**Comment by Adwaith-Rajesh** [comment]
this actually looks good. I'm gonna merge it.. can you update the config file for a version bump... (bump the minor version)

**Comment by Adwaith-Rajesh** [comment]
Thank you for your contribution.

**Comment by Adwaith-Rajesh** [comment]
@builder555 it's live: https://pypi.org/project/pysondb-v2/2.2.0/

**Pull request merged**
